run:
  timeout: 5m
  tests: true
  skip-dirs:
    - vendor
    - migrations

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - misspell
    - gosec
    - gocritic
    - revive
    - unconvert
    - unparam
    - prealloc
    - exportloopref
    - gochecknoinits
    - goconst
    - gocognit
    - gocyclo
    - goerr113
    - gomnd
    - goprintffuncname
    - nakedret
    - noctx
    - nolintlint
    - rowserrcheck
    - sqlclosecheck
    - stylecheck
    - thelper
    - tparallel
    - typecheck
    - varnamelen
    - whitespace
    - wrapcheck
    - wsl

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
  gocyclo:
    min-complexity: 15
  gocritic:
    enabled-tags:
      - performance
      - style
      - diagnostic
    disabled-checks:
      - dupImport
  govet:
    check-shadowing: true
  gosec:
    severity: medium
    confidence: medium
  revive:
    rules:
      - name: exported
        severity: warning
      - name: var-naming
        severity: warning
      - name: package-comments
        severity: warning
      - name: range
        severity: warning
      - name: increment-decrement
        severity: warning
      - name: var-declaration
        severity: warning
      - name: range-val-in-closure
        severity: warning
      - name: range-val-address
        severity: warning
      - name: waitgroup-by-value
        severity: warning
      - name: atomic
        severity: warning
      - name: empty-lines
        severity: warning
      - name: max-public-structs
        severity: warning
        arguments:
          - "0"
      - name: if-return
        severity: warning
      - name: error-return
        severity: warning
      - name: error-naming
        severity: warning
      - name: error-strings
        severity: warning
      - name: receiver-naming
        severity: warning
      - name: unexported-return
        severity: warning
      - name: indent-error-flow
        severity: warning
      - name: errorf
        severity: warning
      - name: blank-imports
        severity: warning
      - name: context-as-argument
        severity: warning
      - name: context-keys-type
        severity: warning
      - name: time-equal
        severity: warning
      - name: time-naming
        severity: warning
      - name: var-naming
        severity: warning
      - name: range
        severity: warning
      - name: increment-decrement
        severity: warning
      - name: var-declaration
        severity: warning
      - name: range-val-in-closure
        severity: warning
      - name: range-val-address
        severity: warning
      - name: waitgroup-by-value
        severity: warning
      - name: atomic
        severity: warning
      - name: empty-lines
        severity: warning
      - name: max-public-structs
        severity: warning
        arguments:
          - "0"
      - name: if-return
        severity: warning
      - name: error-return
        severity: warning
      - name: error-naming
        severity: warning
      - name: error-strings
        severity: warning
      - name: receiver-naming
        severity: warning
      - name: unexported-return
        severity: warning
      - name: indent-error-flow
        severity: warning
      - name: errorf
        severity: warning
      - name: blank-imports
        severity: warning
      - name: context-as-argument
        severity: warning
      - name: context-keys-type
        severity: warning
      - name: time-equal
        severity: warning
      - name: time-naming
        severity: warning

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - gosec
        - goconst
        - gomnd
  max-issues-per-linter: 0
  max-same-issues: 0
