ALTER TABLE worker_task_assignments ADD COLUMN IF NOT EXISTS stake_amount_gstd DECIMAL(18, 9) DEFAULT 0;
ALTER TABLE tasks ADD COLUMN IF NOT EXISTS input_source TEXT DEFAULT 'manual';
ALTER TABLE tasks ADD COLUMN IF NOT EXISTS input_hash TEXT DEFAULT '';
ALTER TABLE tasks ADD COLUMN IF NOT EXISTS orchestration_score_required FLOAT DEFAULT 0;
ALTER TABLE tasks ADD COLUMN IF NOT EXISTS stake_amount_gstd FLOAT DEFAULT 0;
ALTER TABLE tasks ADD COLUMN IF NOT EXISTS certainty_gravity_score FLOAT DEFAULT 0;
ALTER TABLE tasks ADD COLUMN IF NOT EXISTS platform_fee_gstd FLOAT DEFAULT 0;
ALTER TABLE tasks ADD COLUMN IF NOT EXISTS executor_reward_gstd FLOAT DEFAULT 0;
ALTER TABLE tasks ADD COLUMN IF NOT EXISTS constraints_time_limit_sec INTEGER DEFAULT 3600;
ALTER TABLE tasks ADD COLUMN IF NOT EXISTS constraints_max_energy_mwh INTEGER DEFAULT 100;

ALTER TABLE users ADD COLUMN IF NOT EXISTS gstd_balance DECIMAL(18, 9) DEFAULT 0;
ALTER TABLE users ADD COLUMN IF NOT EXISTS gstd_escrow_balance DECIMAL(18, 9) DEFAULT 0;
ALTER TABLE users ADD COLUMN IF NOT EXISTS gstd_frozen DECIMAL(18, 9) DEFAULT 0;

CREATE INDEX IF NOT EXISTS idx_tasks_input_hash ON tasks(input_hash);
