package api

import (
	"distributed-computing-platform/docs"

	"github.com/gin-gonic/gin"
	swaggerFiles "github.com/swaggo/files"
	ginSwagger "github.com/swaggo/gin-swagger"
)

// DocsHandler handles API documentation
type DocsHandler struct{}

func NewDocsHandler() *DocsHandler {
	return &DocsHandler{}
}

// SetupSwagger configures Swagger documentation endpoint using gin-swagger
func (h *DocsHandler) SetupSwagger(router *gin.Engine) {
	// Swagger UI endpoint - gin-swagger will automatically serve the generated docs
	router.GET("/api/v1/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler,
		ginSwagger.URL("/api/v1/swagger/doc.json"),
		ginSwagger.DefaultModelsExpandDepth(-1),
		ginSwagger.DocExpansion("none"),
		ginSwagger.DeepLinking(true),
		ginSwagger.PersistAuthorization(true),
	))

	// Initialize docs package (this will be generated by swag init)
	// The docs package is imported to ensure it's compiled
	_ = docs.SwaggerInfo
}
