// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "https://app.gstdtoken.com/terms",
        "contact": {
            "name": "GSTD Platform Support",
            "url": "https://app.gstdtoken.com",
            "email": "support@gstdtoken.com"
        },
        "license": {
            "name": "MIT",
            "url": "https://opensource.org/licenses/MIT"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/nodes/my": {
            "get": {
                "security": [
                    {
                        "SessionToken": []
                    }
                ],
                "description": "Get list of all nodes registered by the authenticated wallet",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Nodes"
                ],
                "summary": "Get my nodes",
                "responses": {
                    "200": {
                        "description": "List of nodes",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/nodes/register": {
            "post": {
                "security": [
                    {
                        "SessionToken": []
                    }
                ],
                "description": "Register a new computing node for the wallet",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Nodes"
                ],
                "summary": "Register node",
                "parameters": [
                    {
                        "description": "Node registration request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Node registered successfully",
                        "schema": {
                            "$ref": "#/definitions/models.Node"
                        }
                    },
                    "400": {
                        "description": "Invalid request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/payments/payout-intent": {
            "post": {
                "security": [
                    {
                        "SessionToken": []
                    }
                ],
                "description": "Create a payout intent for task executor to claim rewards",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Payments"
                ],
                "summary": "Create payout intent",
                "parameters": [
                    {
                        "description": "Payout intent request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Payout intent created",
                        "schema": {
                            "$ref": "#/definitions/services.PayoutIntent"
                        }
                    },
                    "400": {
                        "description": "Invalid request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/stats": {
            "get": {
                "security": [
                    {
                        "SessionToken": []
                    }
                ],
                "description": "Get statistics for the authenticated user",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Statistics"
                ],
                "summary": "Get user statistics",
                "responses": {
                    "200": {
                        "description": "User statistics",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/tasks": {
            "post": {
                "security": [
                    {
                        "SessionToken": []
                    }
                ],
                "description": "Create a new distributed computing task",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Tasks"
                ],
                "summary": "Create task",
                "parameters": [
                    {
                        "description": "Task creation request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Task created successfully",
                        "schema": {
                            "$ref": "#/definitions/models.Task"
                        }
                    },
                    "400": {
                        "description": "Invalid request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/tasks/{id}": {
            "get": {
                "security": [
                    {
                        "SessionToken": []
                    }
                ],
                "description": "Get detailed information about a specific task",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Tasks"
                ],
                "summary": "Get task by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Task ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Task details",
                        "schema": {
                            "$ref": "#/definitions/models.Task"
                        }
                    },
                    "400": {
                        "description": "Task not found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/users/login": {
            "post": {
                "description": "Authenticate user with TON Connect signature and create session",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Authentication"
                ],
                "summary": "User login",
                "parameters": [
                    {
                        "description": "Login request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Login successful, returns session_token",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Invalid request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Signature validation failed",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/wallet/gstd-balance": {
            "get": {
                "security": [
                    {
                        "SessionToken": []
                    }
                ],
                "description": "Get GSTD token balance from TON blockchain",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Wallet"
                ],
                "summary": "Get GSTD balance",
                "responses": {
                    "200": {
                        "description": "GSTD balance information",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.Node": {
            "type": "object",
            "properties": {
                "country": {
                    "description": "Country code (ISO 3166-1 alpha-2)",
                    "type": "string"
                },
                "cpu_model": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "last_seen": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "ram_gb": {
                    "type": "integer"
                },
                "status": {
                    "description": "online/offline",
                    "type": "string"
                },
                "trust_score": {
                    "description": "Reputation score (0.0-1.0)",
                    "type": "number"
                },
                "updated_at": {
                    "type": "string"
                },
                "wallet_address": {
                    "type": "string"
                }
            }
        },
        "models.Task": {
            "type": "object",
            "properties": {
                "assigned_at": {
                    "type": "string"
                },
                "assigned_device": {
                    "type": "string"
                },
                "budget_gstd": {
                    "type": "number"
                },
                "completed_at": {
                    "type": "string"
                },
                "confidence_depth": {
                    "type": "integer"
                },
                "created_at": {
                    "type": "string"
                },
                "creator_wallet": {
                    "type": "string"
                },
                "deposit_id": {
                    "type": "string"
                },
                "escrow_address": {
                    "type": "string"
                },
                "escrow_amount_ton": {
                    "type": "number"
                },
                "escrow_status": {
                    "type": "string"
                },
                "execution_time_ms": {
                    "type": "integer"
                },
                "executor_reward_ton": {
                    "type": "number"
                },
                "geo_restriction": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "input_hash": {
                    "type": "string"
                },
                "input_source": {
                    "type": "string"
                },
                "is_private": {
                    "type": "boolean"
                },
                "is_spot_check": {
                    "type": "boolean"
                },
                "labor_compensation_ton": {
                    "type": "number"
                },
                "max_energy_mwh": {
                    "type": "integer"
                },
                "min_trust_score": {
                    "type": "number"
                },
                "model": {
                    "type": "string"
                },
                "operation": {
                    "type": "string"
                },
                "payload": {
                    "description": "JSON string",
                    "type": "string"
                },
                "payment_memo": {
                    "type": "string"
                },
                "platform_fee_ton": {
                    "type": "number"
                },
                "priority_score": {
                    "type": "number"
                },
                "redundancy_factor": {
                    "type": "integer"
                },
                "requester_address": {
                    "type": "string"
                },
                "result_data": {
                    "type": "string"
                },
                "result_nonce": {
                    "type": "string"
                },
                "result_proof": {
                    "type": "string"
                },
                "result_submitted_at": {
                    "type": "string"
                },
                "reward_gstd": {
                    "type": "number"
                },
                "status": {
                    "type": "string"
                },
                "task_id": {
                    "type": "string"
                },
                "task_type": {
                    "type": "string"
                },
                "time_limit_sec": {
                    "type": "integer"
                },
                "timeout_at": {
                    "type": "string"
                },
                "validation_method": {
                    "type": "string"
                }
            }
        },
        "services.PayoutIntent": {
            "type": "object",
            "properties": {
                "amount_nano": {
                    "description": "usually 0; contract releases escrow",
                    "type": "integer"
                },
                "executor_address": {
                    "type": "string"
                },
                "executor_reward_ton": {
                    "type": "number"
                },
                "idempotency_key": {
                    "description": "For idempotent requests",
                    "type": "string"
                },
                "nonce": {
                    "description": "Replay attack protection",
                    "type": "integer"
                },
                "payload_comment": {
                    "type": "string"
                },
                "platform_fee_ton": {
                    "type": "number"
                },
                "query_id": {
                    "description": "Transaction query ID for tracking",
                    "type": "integer"
                },
                "task_id": {
                    "type": "string"
                },
                "to_address": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "SessionToken": {
            "description": "Session token obtained from /users/login endpoint",
            "type": "apiKey",
            "name": "X-Session-Token",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "app.gstdtoken.com",
	BasePath:         "/api/v1",
	Schemes:          []string{"https", "http"},
	Title:            "GSTD DePIN Platform API",
	Description:      "API documentation for GSTD Decentralized Physical Infrastructure Network Platform. This API enables distributed computing tasks, worker management, and TON blockchain integration.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
