package services

import (
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"strings"
)

// Unified Identity Protocol — Global Device Namespace
// device_id = hash(wallet_address + platform_fingerprint) to eliminate collisions
// and allow users to see all devices under one wallet.

const prefixUnified = "gstd_"

// GenerateDeviceID produces a deterministic device_id from wallet + fingerprint.
// Format: gstd_<32 hex chars> for URL-safe, readable IDs.
// Same (wallet, fingerprint) always yields same device_id.
func GenerateDeviceID(walletAddress, platformFingerprint string) string {
	if walletAddress == "" || platformFingerprint == "" {
		return ""
	}
	wallet := strings.TrimSpace(walletAddress)
	fp := strings.TrimSpace(platformFingerprint)
	h := sha256.Sum256([]byte(wallet + "|" + fp))
	return prefixUnified + hex.EncodeToString(h[:])[:32]
}

// NormalizeDeviceID returns device_id: either generated from fingerprint or the provided legacy ID.
// If platformFingerprint is set, always generates. Otherwise uses legacyID.
func NormalizeDeviceID(walletAddress, platformFingerprint, legacyID string) string {
	if platformFingerprint != "" && walletAddress != "" {
		return GenerateDeviceID(walletAddress, platformFingerprint)
	}
	return legacyID
}

// IsUnifiedDeviceID returns true if device_id was generated by Unified Identity.
func IsUnifiedDeviceID(deviceID string) bool {
	return strings.HasPrefix(deviceID, prefixUnified)
}

// PlatformFingerprintFromMetadata builds a fingerprint from common metadata fields.
// Used when client doesn't send explicit platform_fingerprint.
func PlatformFingerprintFromMetadata(deviceType, hostname, osName, userAgent string) string {
	parts := []string{}
	if deviceType != "" {
		parts = append(parts, deviceType)
	}
	if hostname != "" {
		parts = append(parts, hostname)
	}
	if osName != "" {
		parts = append(parts, osName)
	}
	if userAgent != "" {
		// Truncate UA to avoid huge strings
		ua := userAgent
		if len(ua) > 200 {
			ua = ua[:200]
		}
		parts = append(parts, ua)
	}
	if len(parts) == 0 {
		return ""
	}
	return strings.Join(parts, "|")
}

// NodeTypeFromMetadata infers node type from request metadata for Unified Registry.
// Returns: "node" | "device" | "unknown"
func NodeTypeFromMetadata(specs map[string]interface{}, deviceType, source string) string {
	if source != "" {
		switch strings.ToLower(source) {
		case "swarm", "agent", "desktop":
			return "node"
		case "browser", "telegram", "mobile":
			return "device"
		}
	}
	if deviceType != "" {
		switch strings.ToLower(deviceType) {
		case "swarm", "desktop":
			return "node"
		case "browser", "telegram", "android", "ios":
			return "device"
		}
	}
	if specs != nil {
		if t, ok := specs["type"].(string); ok && t != "" {
			switch strings.ToLower(t) {
			case "swarm", "compute", "agent":
				return "node"
			}
		}
		if _, hasCap := specs["capabilities"]; hasCap {
			return "node"
		}
	}
	return "unknown"
}

// UserContext holds unified auth state for Hybrid Auth Layer.
type UserContext struct {
	WalletAddress string
	AuthSource    string // "session" | "api_key" | "sovereign" | ""
	UserID        string
	UltraAllowed  bool
}

func (u *UserContext) String() string {
	return fmt.Sprintf("UserContext{wallet=%s, source=%s, ultra=%v}", u.WalletAddress[:min(8, len(u.WalletAddress))], u.AuthSource, u.UltraAllowed)
}
